hlxsites/aem-boilerplate-commerce

- blocks/product-details/product-details.js
- blocks/product-list-page/ProductList.js
- blocks/product-list-page/product-list-page.js
- scripts/commerce.js
- scripts/scripts.js
* Add ACDL initialization, ACDL itself was not added
* Replace MSE usage with direct ACDL usage
* Add search and category related storefront events
Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.hlx.page/
- After: https://plp-acdl--aem-boilerplate-commerce--hlxsites.hlx.live/
> Add storefront events to PLP

- blocks/enrichment/enrichment.js
* Fixes enrichment block when added before PLP block (dataset might not be set).
* Fixes merging of section styles
Test URLs:
- After: 
- https://enrichment-fixes--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://enrichment-fixes--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03
- https://enrichment-fixes--aem-boilerplate-commerce--hlxsites.hlx.live/gear
> Enrichment bug fixes

- blocks/enrichment/enrichment.js
* Enrichments would break if there are `#text` elements returned by `section.childNodes`. So instead `section.children` is used.
Test URLs:
- After: 
- https://enrichment-fix--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://enrichment-fix--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03
- https://enrichment-fix--aem-boilerplate-commerce--hlxsites.hlx.live/products/endurance-watch/24-MG01 (multiple sections)
- https://enrichment-fix--aem-boilerplate-commerce--hlxsites.hlx.live/products/rival-field-messenger/24-MB06 (single section)
- https://enrichment-fix--aem-boilerplate-commerce--hlxsites.hlx.live/gear
> Fix enrichment bug

- scripts/commerce.js
- scripts/delayed.js
- scripts/scripts.js
* Add common `getConsent` method which is used by Commerce functionality to check if a shopper has given consent for certain topics of data collection
* Add warning console output to ensure the method is implemented during projects
* Added consent checks for:
* Storefront events collector
* Product view history
* Purchase history
Test URLs:
- After: https://consent-check--aem-boilerplate-commerce--hlxsites.hlx.live/
> Add getConsent method

- blocks/product-recommendations/product-recommendations.js
- scripts/commerce.js
- scripts/scripts.js
* Improve loading of ACDL to create a larger gap to delayed.js
* Add support for filtering by `typeId` to product recommendations block for use cases where there is more than one unit on a single page.
* Recommendations block is now only rendered when the section it's contained in is in view (mobile only).
* Added checks when reading from ACDL as MSE SDK might set those contexts to `null`.
Test URLs:
- After:
- https://improve-recs--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://improve-recs--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03
- https://improve-recs--aem-boilerplate-commerce--hlxsites.hlx.live/products/hollister-backyard-sweatshirt/MH05
> Improve product recommendations

- blocks/product-list-page-custom/ProductList.js
- blocks/product-recommendations/product-recommendations.js
- scripts/scripts.js
While checking the storefronts events emitted to Snowplow by the boilerplate I noticed the following two errors which are fixed by this PR:
* Recommendations unit context is missing a placement. 
* As we do not know the placement, setting it to an empty string makes the event valid according to the schema.
```json
{
"schemaKey": "iglu:com.adobe.magento.entity/recommendation-unit/jsonschema/1-0-4",
"error": {
"error": "ValidationError",
"dataReports": [
{
"message": "$.placement: is missing but it is required",
"path": "$",
"keyword": "required",
"targets": [
"placement"
]
}
]
}
}
```
* Product page view event requires a shopping cart context.
* Trivial solution for this problem is to initialise the shopping cart context to an empty cart and let the minicart or cart implementation set the …
> Fix invalid storefront events

- blocks/product-details-custom/product-details-custom.js
- blocks/product-details/product-details.js
- blocks/product-list-page-custom/ProductList.js
- blocks/product-list-page-custom/product-list-page-custom.js
- blocks/product-recommendations/product-recommendations.js
- scripts/commerce.js
- scripts/minicart/Minicart.js
- tools/pdp-metadata/pdp-metadata.js
* Remove case changes for product SKUs. Now they are consistently used as they are returned by the API.
* Removed explicit `twitter:_` meta tags as these are generated automatically and Twitter/X also uses OpenGraph (`og:_`) tags as fallback.
* Server-side generated meta tags from #72 are now available for all PDPs.
Test URLs:
- After: 
- https://sku-lowercase--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://sku-lowercase--aem-boilerplate-commerce--hlxsites.hlx.live/gear
- https://sku-lowercase--aem-boilerplate-commerce--hlxsites.hlx.live/products/hollister-backyard-sweatshirt/MH05
- https://sku-lowercase--aem-boilerplate-commerce--hlxsites.hlx.live/drafts/mabecker/product-list-custom
- …
> Remove case changes from product SKUs

- scripts/dropins.js
Apply fix from https://github.com/hlxsites/boilerplate-commerce-dropins/pull/75
Test URLs:
- After: 
- https://dropin-loading--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://dropin-loading--aem-boilerplate-commerce--hlxsites.hlx.live/products/hollister-backyard-sweatshirt/MH05
> Fix loading of dropins with speculation rule pre-rendering

- scripts/commerce.js
Fix #88 
Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.hlx.live/products/invalid-product1234
- After: https://prevent-soft-404-google--aem-boilerplate-commerce--hlxsites.hlx.live/products/invalid-product1234
> fix: prevent soft 404 errors in search engine indexing

- head.html
* Remove `preconnect` tags for Catalog Service as Catalog Service should be proxied via CDN on the same hostname.
Test URLs:
- After: 
- https://remove-preconnect--aem-boilerplate-commerce--hlxsites.aem.live/
- https://remove-preconnect--aem-boilerplate-commerce--hlxsites.aem.live/gear
- https://remove-preconnect--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
> Remove catalog service preconnect tags

- .hlxignore
* Add `.d.ts` to `.hlxignore` to prevent them from being deployed. Those files are only required for local development.
Test URLs:
- After: 
- https://ts-hlxignore--aem-boilerplate-commerce--hlxsites.aem.live/
- https://ts-hlxignore--aem-boilerplate-commerce--hlxsites.aem.live/scripts/__dropins__/storefront-pdp/api/index.d.ts (supposed to be 404)
> Remove .d.ts files from deployment

- .github/workflows/run-e2e-tests.yaml
This PR adds missing `.github/workflows/run-e2e-tests.yaml` file.
> Added missing run-e2e-tests.yaml file to GH workflows

- blocks/product-details-custom/product-details-custom.js
- blocks/product-details/product-details.js
- scripts/commerce.js
- tools/pdp-metadata/README.md
- tools/pdp-metadata/pdp-metadata.js
- tools/pdp-metadata/queries/products.graphql.js
- tools/pdp-metadata/queries/variants.graphql.js
Adds json LD to metadata sheet generation
Test URLs:
- After: https://json-ld-metadata--aem-boilerplate-commerce--hlxsites.aem.live/
https://search.google.com/test/rich-results/result?id=ja86EZFnhOjGkuyOssCR8w
> render json ld to products metadata sheet

- scripts/scripts.js
From @pchoate-adobe 
> This issue came up during the BULK implementation. There was an issue where if you have the EDS header on checkout pages it would try to modify the DOM before the main element was fully ready to work. It was addressed slightly differently on BULK and we thought it should be ported here. Since the LCP check was already in place in this repository it was simply a matter of waiting for the LCP to finish before adding the appear class to the main div.
Test URLs:
- After: https://caed-67--aem-boilerplate-commerce--hlxsites.aem.live/
> CAED-67 Checkout issues 

- blocks/product-recommendations/product-recommendations.css
- blocks/product-recommendations/product-recommendations.js
- cypress/src/assertions/adobeDataLayer.js
- cypress/src/assertions/index.js
- cypress/src/tests/e2eTests/events/initialization.spec.js
- cypress/src/tests/e2eTests/events/initiate-checkout.spec.js
- cypress/src/tests/e2eTests/events/product-page-view.spec.js
- cypress/src/tests/e2eTests/events/recs.spec.js
- cypress/src/tests/e2eTests/events/search-request-sent.spec.js
- cypress/src/tests/e2eTests/events/search-results-view.spec.js
This PR:
1. Adds an "add to cart" button to product recs implementation. The button copy is conditional depending on productType.
2. Triggers "add-to-cart" when that button is clicked, regardless of productType
3. removes observer.disconnect so that product recs scroll out and in to view will re-trigger view event.
Test URLs:
- After: https://prex-events--aem-boilerplate-commerce--hlxsites.aem.live/
> improve product recommendations events

- blocks/product-details-custom/product-details-custom.js
- blocks/product-recommendations/product-recommendations.js
- blocks/product-teaser/product-teaser.js
- scripts/commerce.js
* Reduce amount of data stored in `recommendationsContext` and `productContext` in ACDL.
* Use `urlKey` from Catalog Service instead parsing it from the product URL.
Test URLs:
- After: 
- https://prex-event--aem-boilerplate-commerce--hlxsites.aem.live/
- https://prex-event--aem-boilerplate-commerce--hlxsites.aem.live/drafts/mabecker/product-details-custom
- https://prex-event--aem-boilerplate-commerce--hlxsites.aem.live/drafts/mabecker/product-teaser
> Update recommendationsContext and productContext to include only required data

- styles/styles.css
Instead of using `display:none` on the body during the early eager phase, the commerce boilerplate uses `visibility: hidden`. Content that is hidden that way will still be layouted by the browser and this causes the browser to change the loading priority of images from `low` to `high` which loads images immediately even below the fold before LCP.
develop (breakpoint at scripts.js line 373 before any decoration happens)
visibility-fix (same breakpoint)
Test URLs:
- After: https://visibility-fix--aem-boilerplate-commerce--hlxsites.aem.live/
> fix: set body to display:none initially

- scripts/initializers/pdp.js
I fixed the reference for the custom label used in placeholders. This is an example of how to add and use your placeholder labels within drop-ins, as demonstrated on the custom "Adding to Cart" label used in the boilerplate.
The `labels.pdpCustomAddingtocart` reference from the previous integrations is no longer used since it's replaced with the JSON object returned using the `fetchPlaceholders` method.
Test URLs:
- https://custom-label--aem-boilerplate-commerce--hlxsites.aem.live/
> add custom label

- blocks/product-details/product-details.js
- scripts/aem.js
The Placeholder Spreadsheet property name changed for a one to one mapping of key - values used by all drop-ins. This PR migrates the existing PDP integration in the `main` branch.
Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
- After: https://placeholders-fix--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
> migrate placeholders on main

- scripts/initializers/account.js
- scripts/initializers/auth.js
- scripts/initializers/cart.js
- scripts/initializers/checkout.js
- scripts/initializers/order-confirmation.js
- scripts/initializers/order.js
- scripts/initializers/pdp.js
Fix Issue:
Initializers are not being awaited, triggering renders before the drop-in has fully initialized. This may cause issues where the `initialData` or `langDefinitiones` are needed before rendering. 
Note: PDP was already _awaited_. so there is no need to apply on `main` This PR fixes it for the rest of the drop-ins in `develop`
Test URLs:
- After: https://await-initializers--aem-boilerplate-commerce--hlxsites.aem.live/
- https://await-initializers--aem-boilerplate-commerce--hlxsites.aem.live/products/crown-summit-backpack/24-MB03
> Await Initializers

- blocks/product-recommendations/product-recommendations.js
- scripts/scripts.js
* Ensure that the `shoppingCartContext` is properly detected by the product recommendations block.
* Ensure that the product recommendations block can also handle an empty `shoppingCartContext`.
Test URLs:
- After: 
- https://prex-cart--aem-boilerplate-commerce--hlxsites.aem.live/
- https://prex-cart--aem-boilerplate-commerce--hlxsites.aem.live/cart
> Fix PRex on cart page

- blocks/product-recommendations/product-recommendations.css
Fixes the max width of PREX on page.
Test URLs:
- Before: https://develop--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
- After: https://prex-width--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
> Fixed PREX (width) layout

- scripts/scripts.js
In this PR, I moved the Experiment Plugin's initialization code to execute before the drop-ins' initialization so that drop-ins have an experiment variant and then execute.
Test URLs:
- After: https://experimentation-plugin-load--aem-boilerplate-commerce--hlxsites.aem.live/
> Experimentation Plugin must load before Drop-ins initialization

- blocks/commerce-checkout/commerce-checkout.js
Update order confirmation to align with the requirements for handling `orderRef` and `orderNumber` parameters:
- Signed-in users: Use `orderRef` with order number in the URL.
- Guest users: Use `orderRef` with order token and include `orderNumber` as a separate parameter in the URL.
- After:  https://checkout-order-url--aem-boilerplate-commerce--hlxsites.aem.live/
> USF-1701 Update order confirmation URL

- head.html
Occurs on Safari in iOS: when a user enters text within the checkout page, the page zooms in on the text field and de-centers content within the checkout container. Even when deselecting the text field or finishing filling out the fields, the page remains slightly zoomed and uncenters the page, cutting off minor elements in the header as well as in the shown container.
Solution https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
Test URLs:
- After: https://usf-1783--aem-boilerplate-commerce--hlxsites.aem.live/
> USF-1783 - Disable viewport auto-zoom

- cypress/src/tests/e2eTests/events/recs.spec.js
Temporarily fixes recs test, as the pdp recs api request stopped returning anything, but /gear still returns at least 1 product.
Test URLs:
https://fix-recs-test--aem-boilerplate-commerce--hlxsites.aem.live
> chore: fix recs test

- cypress/src/tests/e2eTests/events/place-order.spec.js
Test URLs:
- After: https://place-order-test--aem-boilerplate-commerce--hlxsites.aem.live/
> Added cypress test for place-order event - part of USF 1655

- cypress/src/tests/e2eTests/events/shopping-cart-view.spec.js
Test URLs:
- After: https://USF-1652--aem-boilerplate-commerce--hlxsites.aem.live/
> Add cypress test for cart event

- blocks/dynamic-block/dynamic-block.css
- blocks/targeted-block/targeted-block.css
- blocks/targeted-block/targeted-block.js
Resolves:
- [LYNX-736](https://jira.corp.adobe.com/browse/LYNX-736): Displaying only one dynamic block for each specified type
- [LYNX-737](https://jira.corp.adobe.com/browse/LYNX-737): Rename Dynamic Block to Targeted Block
Test URLs:
- After: https://lynx-736--aem-boilerplate-commerce--hlxsites.aem.live/
> LYNX-736: Displaying only one dynamic block for each specified type

- .github/workflows/run-e2e-tests.yaml
Skip cypress job if not on the boilerplate template.
Test URLs:
- After: https://skip-cypress-on-fork--aem-boilerplate-commerce--hlxsites.aem.live/
> chore: skip if not on template repo

- blocks/targeted-block/targeted-block.js
Resolves [LYNX-745](https://jira.corp.adobe.com/browse/LYNX-745) Targeted Block not being displayed due to events order issue
Test URLs:
- After: https://lynx-745--aem-boilerplate-commerce--hlxsites.aem.live/
> LYNX-745: Targeted Block not being displayed due to events order issue

- blocks/targeted-block/condition-matcher.js
- blocks/targeted-block/graphql.js
- blocks/targeted-block/targeted-block.js
This PR implements https://jira.corp.adobe.com/browse/LYNX-759
Test URLs:
- After: https://lynx-759--aem-boilerplate-commerce--hlxsites.aem.live/
> LYNX-759: Separate requests for customer group and segment

- cypress/src/support/sessionStorage.js
Testing whether changes in configs (all using prod config now) will break tests
Test URLs:
- After: https://test-pr--aem-boilerplate-commerce--hlxsites.aem.live/
> fix: force cypress to use staging values for now

- README.md
* Update README to make it clear that for initial creation of the configuration HTTP PUT needs to be used.
Test URLs:
- After: https://config-readme--aem-boilerplate-commerce--hlxsites.aem.live/
> Update HTTP methods for site creation in README

- .hlxignore
Ignores images that dont need served by helix
- https://ignore-images--aem-boilerplate-commerce--hlxsites.aem.live
> hlxignore experimentation plugin images

- README.md
- demo-sidekick.json
Adding back instructions and default/demo sidekick config for easier initial development.
Test URLs:
- After: https://demo-sidekick--aem-boilerplate-commerce--hlxsites.aem.page/
> instructions to re-create helix4 sidekick

- demo-config.json
Forgot to add this to the demo config.
Test URLs:
https://storeheader--aem-boilerplate-commerce--hlxsites.aem.page/
> fix: add store header to all

- blocks/product-recommendations/product-recommendations.css
Divs for plp and product recs were overlapping.
Quick fix just adds margin top to the recs div.
Test URLs:
- After: https://fix-recs-overlap--aem-boilerplate-commerce--hlxsites.aem.live/
> fix: quick fix for overlap of plp/prex divs

- blocks/header/header.css
live and preview nav.plain.html differ from content. While that's being worked on, we can add a small change to the nav css to better align the content regardless.
Test URLs:
- After: https://fix-preview-nav--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://fix-preview-nav--aem-boilerplate-commerce--hlxsites.aem.page/
> bugfix: align nav items center

- default-site.json
- demo-config.json
Test URLs:
- After: https://hannessolo-patch-1--aem-boilerplate-commerce--hlxsites.aem.live/
> chore: Add picker config for root category to site public config

- default-fstab.yaml
Change mountpoint to use content.da.live URL
Fix # [USF-2278-starter-content](https://jira.corp.adobe.com/browse/USF-2278)
> Change mountpoint to da.live on aco branch

- demo-sidekick.json
The demo sidekick config should match docs: https://experienceleague.adobe.com/developer/commerce/storefront/get-started/#link-repo-to-commerce-data 
I chose to simply apply whatever is in docs to the sidekick config. An alternative could be a combination, where we also retain the `plugins` prop + array.
Test URLs:
- https://simple-sidekick-cfg--aem-boilerplate-commerce--hlxsites.aem.live
> chore: simplify sidekick config

- tools/site-creator/site-creator.js
Test URLs:
- https://sc-chore--aem-boilerplate-commerce--hlxsites.aem.live
> prevent error logs on each keystroke if user is typing url

- blocks/commerce-checkout/commerce-checkout.js
- package-lock.json
- package.json
Fix #[USF-2451](https://github.com/adobe-commerce/storefront-checkout/pull/72)
Billing form shows when checkbox is checked after reload or sign-in
Test URLs:
- Before: https://suite-release2--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://checkout-beta6--aem-boilerplate-commerce--hlxsites.aem.live/
> updated checkout drop-in to 2.0.0-beta6

- blocks/accordion/accordion.css
- blocks/accordion/accordion.js
- blocks/cards/cards.js
- scripts/aem.js
- styles/styles.css
Adds some changes that were made in `sf-builder`. The `sf-builder` branch is not being merged, as UE integration is, for the time being, to be a manual step for merchants and developers. They will have to clone the boilerplate, and then apply changes from [sf-builder](https://github.com/hlxsites/aem-boilerplate-commerce/pull/421/files), or documented changes from https://main--docket--da-pilot.aem.live/developers/guides/setup-universal-editor.
In that case, to minimize the amount of changes, I am adding some minor patches to files in the boilerplate that were necessary but should have no functional impact.
Test URLs:
- After: https://uesupport--aem-boilerplate-commerce--hlxsites.aem.live/
> chore: improvements from sf-builder for ue compat

- blocks/commerce-checkout/commerce-checkout.js
We added "Fastlane" in the backend for our Luma integration. However, the payment method is not functional in EDS and should be hidden.
https://jira.corp.adobe.com/browse/pay-6255
Test URLs:
- Before: https://payment-services--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://pay-6255-j--aem-boilerplate-commerce--hlxsites.aem.live/
> PAY-6255: Hide "Fastlane" payment method on checkout

- blocks/enrichment/enrichment.js
- scripts/commerce.js
- scripts/initializers/pdp.js
SKU in URL is:
- not great for SEO
- complicated with EDS requirements (only lowercase document paths)
- doesn't make sense with urlKey-only product urls
This change checks metadata first, for a given PDP. This can exist via bulk-metadata, or if metadata table exists per document with the value (ie on products/some-url-key.md, there is metadata block with sku).
This change should be backwards compatible. This change is already in `integration` but we need it sooner than later in main.
Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.aem.page/
- After: https://check-meta--aem-boilerplate-commerce--hlxsites.aem.page/
> chore: Check meta sku first

- scripts/initializers/index.js
Fix AEM Assets decimal dimension compatibility issue to proactively prevent failed image requests when AEM Assets integration is enabled. 
JIRA Ticket: https://jira.corp.adobe.com/browse/ACAP-1139 
Test URLs:
- After: https://acap-1139--aem-boilerplate-commerce--hlxsites.aem.page/
> ACAP-1139: Converts decimal dimensions to integers for AEM Assets compatibility
