blocks/enrichment/enrichment.css
blocks/enrichment/enrichment.js
blocks/product-list-page/product-list-page.js
scripts/scripts.js

Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.hlx.page/
- After: 
- https://enrichment--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://enrichment--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03
- https://enrichment--aem-boilerplate-commerce--hlxsites.hlx.live/accessories

Add enrichment functionality

---

blocks/commerce-checkout/commerce-checkout.js

redirect to order confirmation page after placing the order
- https://checkout-dropin--aem-boilerplate-commerce--hlxsites.hlx.live/checkout
- https://checkout-dropin--aem-boilerplate-commerce--hlxsites.hlx.live/order-confirmation?orderRef=abc

redirect to order confirmation page after placing the order

---

scripts/configs.js

* Configuration files are split by environment now to make it easier to protect them from unwanted access via
* IP allowlisting on CDN level
* https://www.aem.live/docs/authentication-setup-site
Test URLs:
- After: https://split-configs--aem-boilerplate-commerce--hlxsites.hlx.live/

Split config files

---

blocks/product-details/product-details.js

* Add placeholders file with default PDP values
* Add language definition object to PDP dropin
Test URLs:
- After: 
- https://pdp-i18n--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://pdp-i18n--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03
- https://pdp-i18n--aem-boilerplate-commerce--hlxsites.hlx.live/products/hollister-backyard-sweatshirt/MH05

Add placeholders to PDP

---

blocks/product-list-page-custom/product-list-page-custom.js

Test URLs:
- After: 
- https://rm-search-rum--aem-boilerplate-commerce--hlxsites.hlx.live/
- https://rm-search-rum--aem-boilerplate-commerce--hlxsites.hlx.live/search?q=venia
- https://rm-search-rum--aem-boilerplate-commerce--hlxsites.hlx.live/search?q=bag

Remove nullsearch RUM event

---

blocks/product-details/product-details.css
blocks/product-details/product-details.js
scripts/wishlist/api.js

Adds a starting implementation for the wishlist
Test URLs:
- After: https://wishlist--aem-boilerplate-commerce--hlxsites.hlx.live/products/crown-summit-backpack/24-MB03

add wishlist implementation

---

cypress/src/fixtures/index.js
cypress/src/support/index.js
cypress/src/support/waitForResource.js
cypress/src/tests/e2eTests/events/initialization.spec.js
cypress/src/tests/e2eTests/events/initiate-checkout.spec.js
cypress/src/tests/e2eTests/events/product-page-view.spec.js
cypress/src/tests/e2eTests/events/search-product-click.spec.js
cypress/src/tests/e2eTests/events/search-request-sent.spec.js
cypress/src/tests/e2eTests/events/search-results-view.spec.js

This PR will contain fixes to the instrumentation for PREX/LS in the boilerplate, as well as tests for the events.
See [this doc](https://github.com/adobe/commerce-events/blob/main/examples/events/readme.md#required-events) for more details about which events necessary for what metric and which contexts are necessary for which events.
https://jira.corp.adobe.com/browse/USF-876

USF-876: tests events

---

cypress/src/actions/index.js

Test URLs:
- After: https://dev-fix-cypress--aem-boilerplate-commerce--hlxsites.aem.live/

Fix cypress flakyness

---

blocks/modal/modal.css
blocks/modal/modal.js

https://github.com/user-attachments/assets/f572a060-7f7e-4599-8b5e-eb55e2e2afcd
Test URLs:
Before: https://develop--aem-boilerplate-commerce--hlxsites.aem.live/
After: https://bug-modal-window--aem-boilerplate-commerce--hlxsites.aem.live/

EDS-406 Auth | Fix auth modal (or point to issue)

---

cypress/src/actions/index.js
cypress/src/tests/e2eTests/verifyGuestUserCheckout.spec.js
cypress/src/tests/e2eTests/verifyLowStockInfoMessage.spec.js

Test URLs:
Before: https://develop--aem-boilerplate-commerce--hlxsites.hlx.live/
After: https://fix-cypress--aem-boilerplate-commerce--hlxsites.hlx.live/

fix cypress

---

404.html

Fixes 404 import maps
Test URLs:
- Before: https://404-errors--aem-boilerplate-commerce--hlxsites.aem.live/
- https://404-errors--aem-boilerplate-commerce--hlxsites.aem.live/not-found

Fix 404.html not loading

---

head.html
scripts/aem.js
scripts/initializers/account.js
scripts/initializers/auth.js
scripts/initializers/cart.js
scripts/initializers/checkout.js
scripts/initializers/order-confirmation.js
scripts/initializers/order.js
scripts/initializers/pdp.js

Document: https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BEBB6F538-9A48-4CA9-A144-5E4369A444F0%7D&file=placeholders.xlsx&action=default&mobileredirect=true
JSON: https://www.aemshop.net/placeholders.json
Test URLs:
- https://placeholders--aem-boilerplate-commerce--hlxsites.aem.live/
- https://placeholders--aem-boilerplate-commerce--hlxsites.aem.live/products/hollister-backyard-sweatshirt/MH05
- https://placeholders--aem-boilerplate-commerce--hlxsites.aem.live/cart

placeholders integration

---

blocks/product-details/product-details.js

Bug present due to overused "adding" state from pdp slot context.
Test URLs:
- After: https://pdp-adding-bug--aem-boilerplate-commerce--hlxsites.aem.live/

adding to wishlist caused add to cart to show loading state

---

blocks/product-details/product-details.js

Test URLs:
- After: https://merge-prex-bugfix--aem-boilerplate-commerce--hlxsites.aem.live/

Merge PREX bugfix from main into develop

---

blocks/commerce-cart/commerce-cart.js

Test URLs:
- After: https://cart-attribute-slot--aem-boilerplate-commerce--hlxsites.aem.live/

Cart USF 1535 - Cart Summary has a Product Attributes Slot

---

blocks/commerce-cart/commerce-cart.js
blocks/commerce-mini-cart/commerce-mini-cart.js
cypress/src/assertions/index.js

Test URLs:
- After: https://cart-configs-two--aem-boilerplate-commerce--hlxsites.aem.live/

USF 1509 - Cart supports configurations 

---

plugins/experimentation/src/index.js

Experiments plugin is currently broken. This PR updates the plugin to the latest https://github.com/adobe/aem-experimentation/blob/main/src/index.js 
URL for testing:
- https://fix-experiments--aem-boilerplate-commerce--hlxsites.hlx.live/

Fix/Update Experiment Plugin

---

blocks/commerce-cart/commerce-cart.js

Test URLs:
- After: https://USF-1510-demo--aem-boilerplate-commerce--hlxsites.aem.live/

USF-1510 DEMO: Cart Summary has a Footer Slot

---

blocks/commerce-cart/commerce-cart.js

Test URLs:
- After: https://cart-coupon-demo--aem-boilerplate-commerce--hlxsites.aem.live/

Add coupon container to cart for demo

---

package-lock.json
package.json
scripts/__dropins__/tools/LICENSE.md

Test URLs:
- After: https://update-packages-0-38-0--aem-boilerplate-commerce--hlxsites.hlx.live/

update packages to 0.38.0

---

blocks/targeted-block/targeted-block.js

Resolves: [LYNX-742](https://jira.corp.adobe.com/browse/LYNX-742): Handle targeted blocks before cart is initialised
Test URLs:
- After: https://lynx-742--aem-boilerplate-commerce--hlxsites.aem.live/

LYNX-742: Handle targeted blocks before cart is initialised

---

cypress/src/actions/index.js
package.json

Fixed typo.
- After: https://PAY-5859-typo--aem-boilerplate-commerce--hlxsites.aem.live/

PAY-5859: Fixed typo

---

blocks/targeted-block/targeted-block.js

Updated GraphQL query field name
Test URLs:
- After: https://scp-update--aem-boilerplate-commerce--hlxsites.aem.live/

LYNX-734: Correct GraphQL type name CustomerGroup -> customerGroup

---

blocks/targeted-block/qraphql.js
blocks/targeted-block/targeted-block.js

Fixed [LYNX-755](https://jira.corp.adobe.com/browse/LYNX-755): Error when requesting segments for non-default store
Test URLs:
- After: https://lynx-755--aem-boilerplate-commerce--hlxsites.aem.live/

LYNX-755: Error when requesting segments for non-default store

---

blocks/targeted-block/graphql.js

Fixed cart headers for personalisation request
Test URLs:
- Before: https://main--aem-boilerplate--hlxsites.aem.live/
- After: https://cart-headers--aem-boilerplate--hlxsites.aem.live/

Fixed cart headers for personalisation request

---

blocks/targeted-block/condition-matcher.js

Test URLs:
- After: https://lynx-756--aem-boilerplate-commerce--hlxsites.aem.live/

LYNX-756: Google UTM parameters support

---

blocks/header/header.js

Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.aem.page/
- After: https://test-multistore--aem-boilerplate-commerce--hlxsites.aem.page/
EN Multistore: https://test-multistore--aem-boilerplate-commerce--hlxsites.aem.page/drafts/multistore/en/
EN_CA Multistore: https://test-multistore--aem-boilerplate-commerce--hlxsites.aem.page/drafts/multistore/en_ca/

Multistore - Add rootLink to search result

---

README.md
cypress/src/tests/e2eTests/verifyGiftCard.spec.js

Test URLs:
- After: https://test-new-changes--aem-boilerplate-commerce--hlxsites.aem.live/

Update Cypress to be compatible with SCP beta 11 changes

---

blocks/commerce-account-sidebar/commerce-account-sidebar.js

Test URLs:
- After: https://fix-acc-sidebar--aem-boilerplate-commerce--hlxsites.aem.live/

Fix Account Sidebar — Compatible with DA.live

---

cypress/README.md

Test URLs:
- After: https://update-readme-cypress--aem-boilerplate-commerce--hlxsites.aem.live/

Add info on skipped tests

---

cypress/README.md

Test URLs:
- After: https://latest-main1--aem-boilerplate-commerce--hlxsites.aem.live/

Merge latest main

---

blocks/product-list-page-custom/FacetList.js

Test URLs:
- Before: https://fix--aem-boilerplate-commerce--hlxsites.aem.live/

fix for aco

---

tools/site-creator/create-site.js
tools/site-creator/site-creator.js

Fix #461
Test URLs:
- After: https://issue-461--aem-boilerplate-commerce--hlxsites.aem.live/

fix site creation tool error if org doesnt exist

---

cypress/README.md
cypress/src/tests/e2eTests/verifyAuthUserCheckout.spec.js

Test URLs:
- After: https://update-test--aem-boilerplate-commerce--hlxsites.aem.live/

include cancel flow for SaaS

---

blocks/commerce-checkout/commerce-checkout.js
cypress/src/assertions/adobeDataLayer.js
cypress/src/assertions/index.js
cypress/src/fixtures/index.js
cypress/src/tests/e2eTests/events/add-to-cart.spec.js
cypress/src/tests/e2eTests/events/auth.spec.js
cypress/src/tests/e2eTests/events/initialization.spec.js
cypress/src/tests/e2eTests/events/initiate-checkout.spec.js
cypress/src/tests/e2eTests/events/place-order.spec.js
cypress/src/tests/e2eTests/events/product-page-view.spec.js
cypress/src/tests/e2eTests/events/recs.spec.js
cypress/src/tests/e2eTests/events/search-product-click.spec.js
cypress/src/tests/e2eTests/events/search-request-sent.spec.js
cypress/src/tests/e2eTests/events/search-results-view.spec.js
cypress/src/tests/e2eTests/events/shopping-cart-view.spec.js
cypress/src/tests/e2eTests/verifyAuthUserCheckout.spec.js
cypress/src/tests/e2eTests/verifyGuestUserCheckout.spec.js
cypress/src/tests/e2eTests/verifyGuestUserVirtualCheckout.spec.js
cypress/src/tests/e2eTests/verifyLowStockInfoMessage.spec.js
cypress/src/tests/e2eTests/verifyStoreSwitcher.spec.js
cypress/src/tests/e2eTests/verifyUserAccount.spec.js
cypress/src/tests/e2eTests/verifyZeroTotalCheckoutWithGiftCardAndGiftOptions.spec.js

Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.aem.page/
- After: https://E2E-Virtual--aem-boilerplate-commerce--hlxsites.aem.page/

Create an E2E test to cover a virtual item checkout

---

.devcontainer/devcontainer.json

from https://github.com/hlxsites/aem-boilerplate-commerce/pull/74
Test URLs:
- https://devcontainer--aem-boilerplate--commerce--hlxsites.aem.live

chore: adds devcontainer from #74

---

blocks/product-details/product-details.js

Fix [USF-2429](https://jira.corp.adobe.com/browse/USF-2429) and remove unused code
Test URLs:
- Before: https://suite-release2--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://usf-2429--aem-boilerplate-commerce--hlxsites.aem.live/

USF-2429: No move from wishlist when add to cart

---

scripts/commerce.js

Just comments. No QA needed.
Test URLs:
- After: https://comments--aem-boilerplate-commerce--hlxsites.aem.live/

Added JSDocs comments to `commerce.js`

---

blocks/header/header.js
blocks/product-list-page/product-list-page.js
cypress/cypress.saas.config.js
cypress/src/tests/e2eTests/verifyAemAssets.spec.js

URL for testing:
https://acap-1060--aem-boilerplate-commerce--hlxsites.aem.live/

ACAP-1060 Product Discovery dropin compatibility to AEM Assets

---

blocks/product-details/product-details.js
config.json
scripts/commerce.js

Test URLs:
- Before: https://e2e-prex-dropin-aco2--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://e2e-aco-events--aem-boilerplate-commerce--hlxsites.aem.live/

test add to cart event button

---

blocks/commerce-checkout-braintree/README.md
blocks/commerce-checkout-braintree/commerce-checkout-braintree.css
blocks/commerce-checkout-braintree/commerce-checkout-braintree.js
blocks/commerce-checkout-braintree/utils.js
blocks/commerce-checkout/commerce-checkout.css
blocks/commerce-checkout/commerce-checkout.js
blocks/commerce-checkout/utils.js
package.json

Synchronized `commerce-checkout` and `commerce-checkout-braintree` blocks with last Storefront Checkout Drop-in release version.
This is only for **`demos`** purposes.
- [USF-2554](https://jira.corp.adobe.com/browse/USF-2554)

USF-2554: Synchronize Payments tutorial

---

blocks/commerce-checkout-address-lookup/commerce-checkout-address-lookup.js
blocks/commerce-checkout-bopis/commerce-checkout-bopis.js
blocks/commerce-checkout-multi-step/containers.js

Test URLs:
- Before: https://integration--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://update-multistep--aem-boilerplate-commerce--hlxsites.aem.live/

Update multistep checkout demo import path

---

cypress/src/fixtures/index.js
cypress/src/tests/e2eTests/verifyAuthUserWishlistFeature.spec.js
cypress/src/tests/e2eTests/verifyGuestUserCheckout.spec.js
cypress/src/tests/e2eTests/verifyGuestUserWishlistFeature.spec.js
scripts/commerce.js

Test URLs:
- Before: https://integration--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://merge-fix--aem-boilerplate-commerce--hlxsites.aem.live/

Merge main to integration

---

mcp-server/README.md

Test URLs:
- After: https://update-readme--aem-boilerplate-commerce--hlxsites.aem.live/

Update Readme - Enable MCP settings
